#!/usr/bin/env python
from setuptools import setup, find_packages
import os


# Utility function to read README file
def read(fname):
    return open(os.path.join(os.path.dirname(__file__), fname)).read()


setup(
    name='django-celery-downloader',
    version='0.1',
    description="Provides a process for downloading files generated by celery tasks asynchronously.",
    author="Benjamin W Stookey",
    author_email='ben@aashe.org',
    url='https://github.com/aashe/django-celery-downloader',
    long_description=read("README.md"),
    packages=[
        'django_celery_downloader',
        'django_celery_downloader.tests',
        'django_celery_downloader.tests.demo_app',
    ],
    classifiers=[
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Framework :: Django',
    ],
    test_suite='tests.main',
    install_requires=['Django', ],
)
